services:
  api:
    build: .
    container_name: iot-api-container
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:z
    restart: unless-stopped

  mqtt_receiver:
    build: .
    container_name: iot-mqtt-receiver
    command: ["python", "-m", "src.iot_receiver.mqtt_receiver"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data:z
    restart: unless-stopped